# coding: utf-8

"""
    AI Travel Planner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import logging
import os
import sys
from pathlib import Path

import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI

sys.path.append(str(Path(__file__).parent.parent.parent))
from ai_travel_planner.apis.default_api import router as DefaultApiRouter

# ── Logging ──────────────────────────────────────────────
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)

app = FastAPI(
    title="AI Travel Planner API",
    description="AI-powered multi-agent travel planning assistant with HITL approval",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)


if __name__ == "__main__":
    load_dotenv()
    uvicorn.run(
        "ai_travel_planner.main:app",
        host="127.0.0.1",
        port=8000,
        reload=True,
    )